SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecResponseBodyAccess Off

SecAuditEngine RelevantOnly
SecAuditLogType Serial
SecAuditLogFormat JSON
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts ABIJDEFHZ

SecArgumentSeparator &
SecCookieFormat 0
SecTmpDir /tmp
SecDataDir /var/cache/modsecurity

SecPcreMatchLimit 100000
SecPcreMatchLimitRecursion 100000
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyLimit 26214400
SecRequestBodyInMemoryLimit 131072

Include /etc/nginx/modsec/ticketgal/crs-setup-ticketgal.conf
Include /usr/share/modsecurity-crs/rules/*.conf
Include /etc/nginx/modsec/ticketgal/ticketgal-exclusions.conf